### ISSUE TITLE
OImon tables are missing

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmip6-cmor-tables#1]
@dnadeau4 I've just tried to rewrite some `sic` data from the `OImon` tables and this table file seems to be missing from `CMOR 3.0beta1`

**Comment by dnadeau4** [comment]
They are now called Simon tables!



Lawrence Livermore National Laboratory
Atmospheric, Earth and Energy Division
925-423-3123

________________________________
From: Paul J. Durack
Sent: Friday, May 27, 2016 5:14:22 PM
To: PCMDI/cmip6-cmor-tables
Cc: Nadeau, Denis; Mention
Subject: [PCMDI/cmip6-cmor-tables] OImon tables are missing (#1)


@dnadeau4<https://github.com/dnadeau4> I've just tried to rewrite some sic data from the OImon tables and this table file seems to be missing from CMOR 3.0beta1

**Comment by durack1** [comment]
@dnadeau4 it's missing the `sic` variable.. Not sure if there's anything else missing

**Comment by durack1** [comment]
@dnadeau4 looks like the `CMIP5 sic` has become `CMIP6 siconc` is that correct?

**Comment by durack1** [comment]
@dnadeau4 I'm closing this issue - `sic` (or `siconc`) has been found
