### ISSUE TITLE
Missing definitions for dimensions: typebare and typeburnt

### ISSUE THREAD

**Issue by retishsenan** [PCMDI/cmip6-cmor-tables#107]
Hi,
Dimension names **_typebare_** listed in the CMIP6_Lmon.json and CMIP6_Eyr.json tables and **_typeburnt_** listed in the CMIP6_Lmon.json table do not have associate entries in CMIP6_coordinate.json leading to failures when loading these tables. 

Since I don't produce variables associated with these dimensions, I can bypass these errors for the moment by replacing them with another dimension, say _typeland_, that is defined in CMIP6_coordinate.json. However, there might be implications for other users and this might need to be fixed.

Thanks,
Retish Senan
ECMWF

**Comment by dnadeau4** [comment]
@retishsenan This are now in  https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_coordinate.json#L2136-L2179
