### ISSUE TITLE
Unit of tossq

### ISSUE THREAD

**Issue by goord** [PCMDI/cmip6-cmor-tables#11]
In the tossq table, the unit degC, but should this be squared, i.e. degC2?

**Comment by dnadeau4** [comment]
@durack1  @martinjuckes Do you know what are the units for tossq?

**Comment by durack1** [comment]
@dnadeau4 the quantity is degrees C squared - so units are degrees C

**Comment by dnadeau4** [comment]
@durack1  in @taylor13 units were "K2" in his [standard output](http://cmip-pcmdi.llnl.gov/cmip5/docs/standard_output.pdf) file

**Comment by durack1** [comment]
@dnadeau4 that is mean to mean Kelvin^2

**Comment by durack1** [comment]
@dnadeau4 the quantities are the squared values with units of `deg_C` or `1e-3` respectively for `tossq` and `sossq`

**Comment by dnadeau4** [comment]
@goord after discussion, the variable corresponds to a "variance" or a "standard deviation"  although the value is ``squared`` the units stay the same.

**Comment by goord** [comment]
This makes me wonder whether we (EC-Earth) compute it correctly: should we take the square root after averaging the squares of the temperatures?

**Comment by durack1** [comment]
@goord in the Omon tables the comment reads "square of the temperature of liquid ocean, averaged over a day" so if you're calculating this quantity I think you're in good shape..

@StephenGriffies pinging you here if there are any additional clarifications required

**Comment by durack1** [comment]
@goord the information about each of the diagnostics is published in the [Griffies et al (2016, GMD) document](http://www.geosci-model-dev-discuss.net/gmd-2016-77/gmd-2016-77.pdf#page=26) there are a couple of formatting and notation tweaks that we've noted with the pre-print, however these should be resolved when the final version is updated in a couple of weeks (fingers crossed)..

**Comment by durack1** [comment]
@dnadeau4 another candidate for closing
