### ISSUE TITLE
further_info_url should include https, rather than http

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmip6-cmor-tables#117]
Ref PCMDI/cmor#247

The [template](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json#L7367) should be `https://` whereas it is currently `http://` following v6.2.5 of the [CMIP6 Global Attributes, DRS, Filenames, Directory Structure, and CV’s document](http://goo.gl/v1drZl)

**Comment by dnadeau4** [comment]
https://github.com/PCMDI/cmor/commit/773119d3bdff897190dd604c477a5a0e37856b65

**Comment by dnadeau4** [comment]
I forced `https://` in `further_url_info`.
