### ISSUE TITLE
Frequency mon and monC in Amon

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmip6-cmor-tables#119]
Hi,
just a short question: Is it planned to create an individual table for AmonClim or to include the table OmonClim into Omon?
Best regards,
Fabian Wachsmann

**Comment by dnadeau4** [comment]
@taylor13 can you answer this?

**Comment by taylor13** [comment]
@wachsylon There is no OmonClim table.  The ocean monthy-mean climatology fields are in Oclim ,and it will remain independent of other tables.  There is no Aclim table and there won't be one.  The atmospheric monthly mean climatological fields are included in the Amon table.
I'll close this issue, but please reopen if you have further comments.
