### ISSUE TITLE
quick verification of source attribute 

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [PCMDI/cmip6-cmor-tables#120]
Does the source attribute in the netCDF file for CMIP6 have to match the source in the CV? 

E.g. For CM4, the global attribute source - does it have to hold the string below verbatim? 
I see newline characters also. 

source":"GFDL-CM4 (2017): \naerosol: interactive\natmos: GFDL-AM4.1
(Cubed-sphere (c96) - 1 degree nominal horizontal resolution; 360 x 180
longitude/latitude; 33 levels; top level 1 hPa)\natmosChem: unnamed (fast
chemistry, aerosol only)\nland: GFDL-LM4.0\nlandIce: GFDL-LM4.0\nocean:
GFDL-MOM6 (tripolar - nominal 0.25 deg; 1440 x 720 longitude/latitude; 75
levels; top grid cell 0-2 m)\nocnBgchem: GFDL BLING v2\nseaIce: SIS2"

**Comment by aradhakrishnanGFDL** [comment]
@dnadeau4 @durack1 source attribute related question..

**Comment by durack1** [comment]
@aradhakrishnanGFDL apologies for the delayed response.. The only *source* element that is validated is the `source_id`, whereas the `source` is generated from the registered content that modeling groups have provided to us (e.g. GFDL-CM4 is [here](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L1575-L1627)), and if not using CMOR, a modeling group can provide whatever entry they feel appropriate.

@taylor13 @dnadeau4 please confirm if this information is not correct

@aradhakrishnanGFDL if you're happy with this advise, please close this open issue

**Comment by taylor13** [comment]
Yes, that's correct.  source_id must appear in the reference CV (and CMOR CV table), but source is uncontrolled by CMOR and PrePARE.

**Comment by aradhakrishnanGFDL** [comment]
That helps. Thank you.
