### ISSUE TITLE
dimensionless units

### ISSUE THREAD

**Issue by taylor13** [PCMDI/cmip6-cmor-tables#144]
It looks like Martin plans to change all instances of units="1.0" to units = "1" (see https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/275 ).  I'm concerned that data written with current CMOR tables will not pass PrePARe when checked with future CMOR tables (because "1.0" .ne. "1").  Can CMOR/PrePARe be modified to treat "1.0" equivalent to "1"?  Let's discuss.

Also, can PrePare/CMOR be modified to handle the "basin" case when "units" should not be appear in the netCDF file?

**Comment by dnadeau4** [comment]
I did change the `"1.0"` and `"1"` issue for dimensionless, did not do anything about basin units.  
Since `basin:units`  is a variable attribute,  it is use as ESGF search facet, I think it is a low priority and is an exception case.

**Comment by taylor13** [comment]
Agreed that basin case is low priority,  Martin's tables set units="1", so we can assume data providers will include a units="1" attribute attached to basin.  So I guess PrePARE will be happy.  If you agree, then we can close this issue.

**Comment by dnadeau4** [comment]
agree
