### ISSUE TITLE
source_id and experiment_id updated in CMIP6_CVs

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmip6-cmor-tables#151]
Some changes to `source_id` and `experiment_id` were just implemented [WCRP-CMIP/CMIP6_CVs#466](https://github.com/WCRP-CMIP/CMIP6_CVs/pull/466/files), so it's important that these are pulled across to the `CMIP6_CV.json` promptly next week

@dnadeau4 @taylor13

**Comment by taylor13** [comment]
If this has been done, this issue can be closed.

**Comment by taylor13** [comment]
@dnadeau4 If this has been done, this issue can be closed.

**Comment by taylor13** [comment]
@dnadeau4 @doutriaux1   Can this issue be closed?
