### ISSUE TITLE
"location" not needed

### ISSUE THREAD

**Issue by taylor13** [PCMDI/cmip6-cmor-tables#155]
in the coordinates.json file there is a variable called "location", but this isn't in Martin's data request and I don't think it is needed?  How does it get introduced into the CMOR table?

**Comment by taylor13** [comment]
@doutriaux1 Do you know the answer to the above question?

**Comment by doutriaux1** [comment]
some must come from an old cmip5 table

**Comment by doutriaux1** [comment]
@taylor13 I see it at: https://github.com/PCMDI/xml-cmor3-database/blob/master/tables/dreq.xml

It appears to come from Martin no?

**Comment by taylor13** [comment]
This seems to be not needed.  Is dreq.xml directly from Martin, or do we take his xml and revised it with CMIP5 stuff?
In any case I'll try to close it.  It's not worth chasing this down.

**Comment by doutriaux1** [comment]
let's ask @dnadeau4

**Comment by taylor13** [comment]
@dnadeau4 Do you create cmor3 tables based on https://raw.githubusercontent.com/PCMDI/xml-cmor3-database/master/docs/dreq.xml or on  https://github.com/PCMDI/xml-cmor3-database/blob/master/tables/dreq.xml  or on both?

I think the latest xml is https://raw.githubusercontent.com/PCMDI/xml-cmor3-database/master/docs/dreq.xml and I don't think it includes "plev7" or "location"  as dimensions, but both of these dimensions appear in the CMIP6_coordinate.json table.  Do you know how they get there?

**Comment by dnadeau4** [comment]
`location` is used by `curtain`.. in cf3hr_0.json. 

https://github.com/PCMDI/cmor/blob/master/Test/test_cmor_grid_alejandro.f90

**Comment by dnadeau4** [comment]
This is the one we use.
https://raw.githubusercontent.com/PCMDI/xml-cmor3-database/master/docs/dreq.xml

**Comment by doutriaux1** [comment]
Thanks @dnadeau4 ! I thought you were still off. Welcome back!

**Comment by taylor13** [comment]
It is possible that "plev" is used in another test case (like "location").  In general it would be better to construct tests that don't depend on variable names not already defined for CMIP6; then we wouldn't have to include these non-CMIP6 dimensions.
Also I would be interested in how these dimensions got into the coorrdinates.json file.  Most of the stuff in that file presumably comes from https://raw.githubusercontent.com/PCMDI/xml-cmor3-database/master/docs/dreq.xml which doesn't include either plev or location.  

Let's keep this issue open, but consider it low priority.

**Comment by taylor13** [comment]
@mauzey1 Do you know the answer to this question:
"Also I would be interested in how these dimensions got into the coorrdinates.json file. Most of the stuff in that file presumably comes from https://raw.githubusercontent.com/PCMDI/xml-cmor3-database/master/docs/dreq.xml which doesn't include either plev or location."
