### ISSUE TITLE
Wrong cell_measures in table 01.00.21 

### ISSUE THREAD

**Issue by senesis** [PCMDI/cmip6-cmor-tables#157]
In  somes tables some variables (e.g. SImon table, sidmasstranx and  sidmasstrany), have cell_measures="--MODEL" or "--OPT" . This is consistent with DR content, but not with the CF convention , which states : 

> For the moment, "area" and "volume" are the only defined measures,

The CMOR software should be fixed to allow both an empty cell_measure attribute in such cases, AND the presence of these values for coping with any  choice done by the data producers  when they did generate the data

**Comment by taylor13** [comment]
@dnadeau4 can confirm, but I think when cell_measures in the CMOR table has either "--MODEL" or "--OPT", both CMOR3 doesn't write this attribute and PrePARE doesn't check it.  This means if you include a cell_measures attribute for such variables, it won't be checked by PrePARE for compliance with CF, and your file will be published (unless the CF checker objects).

**Comment by taylor13** [comment]
@senesis :  note also that there are some additional problems with cell_measures for sea ice variables discussed at:  https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/252

**Comment by dnadeau4** [comment]
@taylor13 `CMOR` does not write `cell_measure` when it is set to `--MODEL` or `--OPT` in the `input table` and `PrePARE` does not check this attribute if `--MODEL` or `--OPT` is found in the `input table`. 

In this case the data provider can write any text he/she seems fit and no validation is made.

**Comment by senesis** [comment]
Form which version of PrePARE ?

**Comment by dnadeau4** [comment]
That code was added in August 17th 2017 and has been there since 3.2.6.  Is this causing you any trouble?  

```python
                if key == "cell_measures":
                    if((table_value.find("OPT") != -1) or (table_value.find("MODEL") != -1)):
                       continue
```
https://github.com/PCMDI/cmor/blob/master/LibCV/PrePARE/PrePARE.py#L575-L577

**Comment by dnadeau4** [comment]
Actually this is in the `else` section when the attribute is **not** in the file.  

Somebody needs to move this code at a higher lever, since if the data provider set this attribute, it will be compare to `OPT` or `MODEL`.    I wanted to remove "OPT" or "MODEL" from the CMIP6 tables since it is never used by PrePARE or CMOR3,  but I was voted down.  

Sorry to see that this is giving you trouble too.

**Comment by taylor13** [comment]
@senesis @dnadeau4  Do we need to modify CMOR / PrePARE to handle this?  Or has it been fixed already?

**Comment by taylor13** [comment]
Having not heard to the contrary, let's assume there is no changes needed in CMOR or its tables, so I'll close this.
