### ISSUE TITLE
Should change out_name for typec3pft and typec4pft

### ISSUE THREAD

**Issue by senesis** [PCMDI/cmip6-cmor-tables#163]
[This issue](https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/303 ) calls for a change in CMOR tables regarding out_name of dimensions typec3pft and typec4pft, (and this, whatever the capability of CMOR to handle two scalar coordinates)

CNRM-CERFACS and IPSL will use  "out_name=pfttype"
CNRM uses version 01.00.21 of the tables

**Comment by taylor13** [comment]
We need to review how CMOR handles this, but you are right that these two scalar dimensions can't have the same out_name.

**Comment by taylor13** [comment]
@doutriaux1 I think this issue can be closed.  It was addressed by Martin changing the tables.

**Comment by senesis** [comment]
The issue can be closed only for centers which can use that fixed DR version. But please note that for the other ones, PrePARE must use tables that are consistent with the choice they had to make.

**Comment by taylor13** [comment]
I don't think PrePARE checks coordinate information, so using earlier tables shouldn't impede publication of a variable that has different dimensions than the latest table.
