### ISSUE TITLE
version tagging of CMOR tables

### ISSUE THREAD

**Issue by taylor13** [PCMDI/cmip6-cmor-tables#164]
As described in  https://goo.gl/86C4ZB we need to tag the CMOR tables.  I'll copy the text here, so that it can be implemented.  I think the agreed approach is as follows:

These tables are based on the reference CVs, the DREQ, some CF-mandated information about vertical coordinate formulas and grids, and some additional information (in CMIP6_CVs.json) mandated by the CMIP6 data specifications.

The version number consists of 3 integers separated by “.” (e.g., 6.1.21)

- The first digit indicates that the tables are for CMIP6.
- The second integer is incremented whenever either the 2nd and/or 3rd integer in the CV version number changes
- The last integer must be consistent with the last integer in the DREQ version number.

The github repository will be updated daily (by running a cron job) to ensure that the tables remain consistent with updates and additions to “source” and “institution”, which are expected to occur frequently.  These intermediate updates will not be tagged in the git repository and only a group that changes/adds a source or institution will need to obtain an untagged new version of the CMOR tables.

If anything changes in the CMOR tables other than an update or addition to “source” and “institution”, a tag will be used to indicate that this represents an important new version.  

The annotation should include the versions of the DREQ and CMIP6 CV collection on which it is based (even though the DREQ version is implied by the third integer of the CMOR table version), and the latest version of CMOR that exists at the time the CMOR tables were generated.  A tag would look something like 
5c4bbac517cb2053c6d43957d552cd435809055a refs/tags/6.1.22 (CMIP6_CVs-6.2.3.2/DREQ-01.00.22/CMOR-3.3.1)

**Comment by dnadeau4** [comment]
Done 
```
git tag -n         
6.0.11          CMIP6_CVs-6.2.0.5/DREQ-01.00.11/CMOR-3.2.4
6.0.12          CMIP6_CVs-6.2.0.5/DREQ-01.00.12/CMOR-3.2.4
6.0.13          CMIP6_CVs-6.2.0.6/DREQ-01.00.13/CMOR-3.2.5
6.0.14          CMIP6_CVs-6.2.0.6/DREQ-01.00.14/CMOR-3.2.5
6.0.15          CMIP6_CVs-6.2.0.6/DREQ-01.00.15/CMOR-3.2.7/CMOR-3.2.6
6.0.16          CMIP6_CVs-6.2.0.8/DREQ-01.00.16/CMOR-3.2.8
6.0.17          CMIP6_CVs-6.2.0.9/DREQ-01.00.16/CMOR-3.2.8
6.0.18          CMIP6_CVs-6.2.0.9/DREQ-01.00.16/CMOR-3.2.8
6.0.19          CMIP6_CVs-6.2.0.10/DREQ-01.00.19/CMOR-3.3.0
6.0.19a         CMIP6_CVs-6.2.0.10/DREQ-01.00.19a/CMOR-3.3.0
6.0.20          CMIP6_CVs-6.2.0.10/DREQ-01.00.20/CMOR-3.3.0
6.0.21          CMIP6_CVs-6.2.0.11/DREQ-01.00.21/CMOR-3.3.1
6.1.22          CMIP6_CVs-6.2.3.1/DREQ-01.00.22/CMOR-3.3.1
```
```
git describe       
6.1.22
```

**Comment by taylor13** [comment]
Excellent!
