### ISSUE TITLE
Value of attribute cell_methods includes comment

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmip6-cmor-tables#165]
Hi,
in SImon, variable sithick has:
 "cell_methods": "area: time: mean where sea_ice (comment: mask=siconc or siconca)".
The CF conventions 7.3.2. say:
"If  there  is  both  standardized  and  non-standardized  information,  the  non-standardized  follows  the
standardized  information  and  the  keyword  comment: .  If  there  is  no  standardized  information,  the
keyword  comment:  should  be  omitted". 
Therefore, the comment for sithick should be omitted, shouldn't it?
Thanks and best regards,
Fabi

**Comment by taylor13** [comment]
This issue is now submitted to a different repository shown above, so it can be closed.

**Comment by taylor13** [comment]
@doutriaux1 This issue can be closed.
