### ISSUE TITLE
SImon sidivvel dimensions include "time1"

### ISSUE THREAD

**Issue by oloapinivad** [PCMDI/cmip6-cmor-tables#167]
Not sure if this is the right place to report it, but I found out that in table SImon var sidivvel has a ill-defined dimension which reads "time1". 
I think this should be "time" but please correct me if I am wrong (if this is the case, it is a problem of our cmorization tool and I will contact the people in charge of it).
Best,
Paolo

`````
 "sidivvel": {
            "frequency": "monPt", 
            "modeling_realm": "seaIce", 
            "standard_name": "divergence_of_sea_ice_velocity", 
            "units": "s-1", 
            "cell_methods": "area: mean where sea_ice (comment: mask=siconc) time: point", 
            "cell_measures": "area: areacello", 
            "long_name": "Divergence of the sea-ice velocity field", 
            "comment": "Divergence of sea-ice velocity field (first shear strain invariant)", 
            "dimensions": "longitude latitude time1", 
            "out_name": "sidivvel", 
            "type": "real", 
            "positive": "", 
            "valid_min": "", 
            "valid_max": "", 
            "ok_min_mean_abs": "", 
            "ok_max_mean_abs": ""
        }, 
`````

**Comment by taylor13** [comment]
"time1" indicates that this represents a synoptically (instantaneously) sample field and isn't a time-mean.  It does appear suspicious, but we should check with the sea ice experts before changing.
I also noticed that in Table Emon, the variable  ec550aer has "time1" coordinate but cell_methods="area:time:mean"  These two specifications are inconsistent.
Issues concerning the variables and attributes in the data request should be addressed at  https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues   , so I'll transfer this issue to there.

**Comment by taylor13** [comment]
I think this issue can now be closed.

**Comment by oloapinivad** [comment]
thanks for the explanation

**Comment by ehogan** [comment]
Apologies for commenting on an old ticket, but there are four variables in the `SImon` MIP table with a frequency of `monPt`; shouldn't these variables belong in a `SImonPt` MIP table?

**Comment by doutriaux1** [comment]
@taylor13 ?

**Comment by taylor13** [comment]
For CMIP5 the answer would probably have been yes.  For CMIP6 tables there is less consistency between tables and sampling options.  Tables have, for example, been added even when unneeded.  Unless these variables are also sampled as monthly means, there is no need to put them in a separate table.  

I'm still not sure why these 4 variables have been saved as point samples.  I don't think they were called for in CMIP5.  Maybe you would want to check with Martin (or your sea ice experts).

**Comment by ehogan** [comment]
I have been told that CICE cannot produce any instantaneous data; @martinjuckes do you know anything about this?
