### ISSUE TITLE
plev7: not needed for CMIP6

### ISSUE THREAD

**Issue by taylor13** [PCMDI/cmip6-cmor-tables#172]
The vertical coordinate appears in the CMIP6_coordinate.json file, but it is not found in the data request so it is not needed.  (plev7h and plev7c are needed though).

**Comment by taylor13** [comment]
see https://github.com/PCMDI/cmip6-cmor-tables/issues/155#issuecomment-409722377 for related issue.

**Comment by gleckler1** [comment]
@taylor13

**Comment by taylor13** [comment]
Was this meant to be closed?
