### ISSUE TITLE
Update to dreq 01.00.24

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmip6-cmor-tables#184]
@dnadeau4 @doutriaux1 we're behind the [latest dreq version `01.00.24`](http://clipc-services.ceda.ac.uk/dreq/index.html), with 01.00.23 the current version of these tables. It would be great to update these to the latest.

**Comment by doutriaux1** [comment]
@durack1 I have done this in my half level branch, plan on pushing this today.

**Comment by doutriaux1** [comment]
@durack1 actually there's some noise about these see and chime at: https://github.com/PCMDI/cmor/issues/355

**Comment by matthew-mizielinski** [comment]
Before the update to data request version `01.00.24` is released could you ensure that the long name of the longitude in the CMIP6_coordinate.json file (line 873 in #182) is set to `longitude`. The error in the data request was identified in issue cmip6dr/Request#82

I think this issue could result in an incorrect long name in the vast majority of output files produced using version 01.00.24 if not fixed.

**Comment by durack1** [comment]
@taylor13 ping

**Comment by taylor13** [comment]
@matthew-mizielinski @doutriaux1 Looks like long name is now "Longitude", so I think this can be closed.
