### ISSUE TITLE
data_specs_version < 1.00.06

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmip6-cmor-tables#190]
Hi,
are there still tables according to DReq versions lower than 1.00.06? I could find neither a branch nor a tag for such versions.

We have an institute which used a DReq version 1.00.03 for their simulations. We would like to check it against the corresponding DReq version.
Best regards,
Fabi

**Comment by wachsylon** [comment]
Found it! There is a commit in the old branch for cmor-3-2-3.

**Comment by taylor13** [comment]
@wachsylon could you please inform the group using data requests earlier than 1.00.21 that their data will (most likely) be unfit for publication in the CMIP6 ESGF archive?
thanks,
Karl

**Comment by taylor13** [comment]
Glad to hear it.  It would be great if the group would contact me or one of the many other folks who can facilitate meeting the CMIP6 publication requirements.  Doing it on their own could lead to unforeseen problems.
cheers,
Karl

**Comment by wachsylon** [comment]
The persons of the group already have the link to this conversation so maybe they will join :)
In the mean time, I develop a script which uses CMOR to create the compliant output of their data. I will of course share occurring issues in the CMOR-github.
