### ISSUE TITLE
must_have_bounds=yes for lambda550nm in CMIP6_coordinate.json causes cmor_variable Fortran function to fail

### ISSUE THREAD

**Issue by IngoBethke** [PCMDI/cmip6-cmor-tables#203]
When trying to write the variable od550aer of table CMIP6_AERmon using the cmor_variable Fortran function, I receive the error:

! Error: axis: lambda550nm (table: AERmon) must have bounds, you did not pass any when creating it via cmor_axis

On closer inspection, the error is caused by the condition must_have_bounds=yes and bounds_values="" for lambda550nm specified in CMIP6_coordinate.json. Please note that I did not explicitly instruct the cmor3 library to add the lambda550nm information. The cmor3 library does it automatically. 

Changing must_have_bounds to no (as it is for height2m) in the CMIP6_coordinate.json fixes the problem. Let me know if you think otherwise.

**Comment by taylor13** [comment]
Yes, this dimension should have "no" for "must_have_bounds".  The CMOR tables are generated from the "data request" where it will have to be fixed.  When it is, we will update the CMOR tables.  I will contact Martin J. to request this correction.
thanks.
Karl

**Comment by taylor13** [comment]
The must_have_bounds has now been corrected in release 01.00.28,so I will close.
