### ISSUE TITLE
Standard name and long name of latitude and longitude for variables on tripolar grid

### ISSUE THREAD

**Issue by matthew-mizielinski** [PCMDI/cmip6-cmor-tables#204]
We're getting CMOR output that fails CF standards checks processing our ocean data, because the `latitude` and `longitude` variables don't have a standard name or long name attribute.

This has been discussed before at the end of PCMDI/cmor#273 (but after it was closed).

The changes needed are pretty straightforward; [in this section of CMIP6_grids.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/69bbb7c981c9c24e2cfffa38bf9a3d50e81d4647/Tables/CMIP6_grids.json#L116) the `standard_name` and `long_name` entries for `latitude` and `longitude` need to be set, (but not on the `vertices_*` entries).

I think this has already been agree to on PCMDI/cmor#273, but feel free to contradict me if you think otherwise. 

I expect to pick up the mip_tables corresponding to data request version 01.00.27 when Martin releases it for our first HadGEM3/UKESM1 production runs, so it would be handy if we could squeeze this in before a corresponding mip tables release is cut.

**Comment by taylor13** [comment]
Yes, I think this was fixed at one point, but somehow the fix got reversed.  Charles will fix it again before releasing the new data request 27 version of the CMOR tables.

**Comment by doutriaux1** [comment]
fixed by https://github.com/PCMDI/cmor/pull/380 and https://github.com/PCMDI/cmip6-cmor-tables/pull/205

**Comment by taylor13** [comment]
@matthew-mizielinski @doutriaux1 This looks like it's been fixed now, so we can close this issue.
