### ISSUE TITLE
Link between cmip6-cmor-tables and cmor/TestTables

### ISSUE THREAD

**Issue by pabretonniere** [PCMDI/cmip6-cmor-tables#21]
Hi,

Could you please let me know the link there is between this project ( cmip6-cmor-tables) and the TestTables inside the cmor project please? I see they are very similar but not exactly identical. Are the TestTables regularly (automatically?) updated from the cmip6-cmor-tables? Or is the other way around?
To get the more up-to-date CMIP6 tables, where do you recommend me to get them from?

Thanks a lot,
Best regards,

**Comment by pabretonniere** [comment]
Tagging @dnadeau4 as I am not sure who receives notifications of the issues by default.

**Comment by dnadeau4** [comment]
They are identical, but some test required it own tables.  For example, test_lots_of_variable will create about 500 hfls variable which are found in the TestTables directory.   

TestTables have some cf3hr tables as well that are needed for some tests.   You can link directly to Your "Tables" directory to the "cmip6-cmor-tables",  most tests use them....
