### ISSUE TITLE
out_name empty for x y

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [PCMDI/cmip6-cmor-tables#214]
out_name is set to "" here. Just wanted to point this out. Not sure if its an issue. 

   "y": {
            "long_name": "y coordinate of projection", 
            "standard_name": "projection_y_coordinate", 
            "out_name": "", 
            "units": "m", 
            "type": "", 
            "axis": "Y"

..

https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_grids.json#L94

**Comment by doutriaux1** [comment]
@taylor13

**Comment by taylor13** [comment]
@doutriaux1  I think you added the projections option.  Do we have a test for this option?  We should check that projection_y_coordinate is being treated correctly.

**Comment by doutriaux1** [comment]
@taylor13 see: https://github.com/PCMDI/cmor/blob/master/Test/test_python_CMIP6_projections.py

**Comment by taylor13** [comment]
thanks. Could you provide a link (or email me) an ncdump of the file produced by the above test?
thanks.

**Comment by taylor13** [comment]
the output file looks o.k.  "x" and "y", which don't have out_names specified are written as variables dimensions x(x) and y(y).  

I suggest that to avoid worrying about whether this is a problem or not sometime in the future, that we now define the outnames in grids.json as "x" and "y".  then run the test code again and check that there aren't any problems.

**Comment by mauzey1** [comment]
Karl and I checked on this.  The default is for the outname to be the same as the entry (e.g., outname will be "y" by default if the entry name is "y".)  No changes are necessary.
