### ISSUE TITLE
lat/lon inconsistent across CMIP6_grids and CMIP6_coordinates

### ISSUE THREAD

**Issue by zklaus** [PCMDI/cmip6-cmor-tables#215]
In `CMIP6_grids.json` the `out_name` for `latitude` is given as `latitude`, whereas the (slightly newer) `CMIP6_coordinates.json` gives it as `lat`. This leads to confusion wrt the correct output.

Am I missing something or would it be better to harmonize this?

**Comment by taylor13** [comment]
The distinction is that in the coordinates file latitude and longitude have out_names "lat" and "lon", respectively, because they are true dimensions of the variable being written and for historical reasons when used as  a dimension they are abbreviated so one could write, for example, tas(time,lat, lon, time).  In the grids file, latitude and longitude are ancillary coordinates that are functions of the true dimensions (e.g., x, and y), so we can write tas(time,y,x), latitude(y,x) and longitude(y,x). 

Do you still think it is confusing for them to have different names?

**Comment by zklaus** [comment]
Well, I think there still can be some confusion, particularly for non regular native grids.
For example, looking at the data that has been published on the ESGF so far, GFDL seems to use `lon` and `lat` as `out_name` for at least some Omon variable (see [1]), whereas IPSL even has `nav_lat` and `nav_lon` ([2]). Of course you might say that these are simply bugs in the data, but at least in the case of GFDL the file seems to exhibit a good standards compliance, surely stemming from significant effort.

I think the confusion comes from the fact that the variable definition (let `tos` in `Omon` serve as an example) mentions only `dimensions` with their respective longname where it can be resolved equally through coordinate and grids table.

Probably that is clarified in another CMIP6 document, but I could not find the relevant information.

Conceptually, for me, there is not enough of a difference between the variables defining the dimensional versions of the coordinates and those concerning the auxiliary ones.

[1] tos_Omon_GFDL-CM4_piControl_r1i1p1f1_gn_015101-017012.nc
[2] tos_Omon_IPSL-CM6A-LR_1pctCO2_r1i1p1f1_gn_185001-199912.nc

**Comment by taylor13** [comment]
As I recall, you are probably right that the CMIP6 specifications would allow ancillary coordinates defined for grid projections other than latxlon to be named anything the user likes (e.g., latitude, nav_lat, or lat).  Such files will be consistent with the CF metadata standards and CMIP6 specs, but may be inconsistent in this regard with CMOR-written files.  

The document describing CMIP6 output requirements is  https://goo.gl/neswPr  and the relevant discussion is in item 9 under the section titled  "Requirements for coordinate variables".

**Comment by zklaus** [comment]
Thanks for your answer! That does clear it up sufficiently: To locate the latitude/longitude information one has to look at the coordinate attribute and identify the correct variable regardless of name by its `standard_name` attribute.

I am still a bit puzzled what is the purpose of the variable entries in `CMIP6_grids.json` and why the variable name for such fundamental attributes wouldn't be prescribed, but that is beyond the scope of this ticket, which, from my perspective can be closed.

Thanks again!

**Comment by taylor13** [comment]
It appears no changes are needed in CMOR, so I will close this.
