### ISSUE TITLE
Data type of variables in CMIP6_grids.json

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmip6-cmor-tables#219]
Hi,
I was working with CMOR and I was wondering why the grid coordinates `vertices_latitude` and `vertices_longitude` in my output file are given as `type float` although I call `cmor_grid` with `type double`. I added `"type":"double"` to the coordinate variables in  `CMIP6_grids.json`, repeated it and got an output with `vertices_latitude` and `vertices_longitude` in double format.

Is "float" the default format for variables not requested in any format? But why the downgrade at all? Since we can provide the data format within the CMOR function `cmor_grid`, shouldn't CMOR be able to process both coordinate data types? Should we maybe add `"type":"double"` to all the coordinate variables in  `CMIP6_grids.json`? 
Best regards,
Fabi

**Comment by taylor13** [comment]
Yes, I agree.  We should specify type "double" for all variables in CMIP6_grids.json *except* the "index" variables, which are integers.  Thanks @wachsylon for noticing this.

**Comment by mauzey1** [comment]
The non-index variables in CMIP6_grids.json are now using type "double".  These changes have been released with version 01.00.29 of the tables and CMOR 3.4.0.

Closing issue.
