### ISSUE TITLE
Possible typo in table Omon (and maybe others)

### ISSUE THREAD

**Issue by aearamos** [PCMDI/cmip6-cmor-tables#221]
Hi, I noticed that variable "vo" in table CMIP6_Omon is given as:
 "comment": "Prognostic x-ward velocity component resolved by the model.",

Shouldn't it be "Prognostic y-ward velocity component resolved by the model."?

I have not checked other tables, only Omon. 

Thanks!

**Comment by martinjuckes** [comment]
Thanks ... I'll correct that in the 01.00.29 data request release.

**Comment by taylor13** [comment]
Confirmed!  This has been corrected in 01.00.29.
