### ISSUE TITLE
01.00.28 release?

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmip6-cmor-tables#222]
Will there be a release for the 01.00.28 version of the MIP tables?

**Comment by taylor13** [comment]
We just released it.  See release listing at: https://github.com/PCMDI/cmip6-cmor-tables/releases .  Also tag:  https://github.com/PCMDI/cmip6-cmor-tables/releases/tag/6.2.15.0

**Comment by ehogan** [comment]
Great, thanks @taylor13 and @mauzey1! :)
