### ISSUE TITLE
Naming in CMIP6_CV.json:  DynVarMIP or DynVar 

### ISSUE THREAD

**Issue by treerink** [PCMDI/cmip6-cmor-tables#228]
While updating the MIP lists for the EC-Earth3 configurations in [`CMIP6_CV.json`](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json), I saw that DynVar MIP is named **DynVarMIP** in this [`CMIP6_CV.json`](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json) file while in the CMIP6 data request tool `drq` the only name is **DynVar**. Is the naming incorrect in this [`CMIP6_CV.json`](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json) file?

**Comment by treerink** [comment]
Ok, I hope that this inconsequent naming doesn't have an effect in any chain. Actually, seeing all the naming, I agree that it looks more like an inconsequent naming in `drq`, but I doubt if they want to change it  in this stage.

Closing.

**Comment by taylor13** [comment]
I've registered an issue about this on the data request github site.
