### ISSUE TITLE
Problem with cmor.zfactor in table 6hrLev

### ISSUE THREAD

**Issue by tommibergman** [PCMDI/cmip6-cmor-tables#230]
[3d-modellevels.tar.gz](https://github.com/PCMDI/cmip6-cmor-tables/files/2779789/3d-modellevels.tar.gz)
I get this error for defining zfactor for ec550aer in 6hrLev:

`You defined variable 'ps' (table 6hrLev) with axis id 'time1' which is not part of this variable according to your table, it says: ( time latitude longitude )`

As I understand I am using 6hrLev, which according to 1.00.29 tables has time1 as time index for ps. As I understand the error message I should define it as time not time1. Do I understand this correct?

I also tried using time, which works for ps variable but not for ec550aer. 

I attach here a modified example from the CMOR-library examples, which fails on zfactor definition of ps. If you change the "time1" to "time" it will write the zfactor but fails on writing of ec550aer due to wrong time-index.

[3d-modellevels.tar.gz](https://github.com/PCMDI/cmip6-cmor-tables/files/2779538/3d-modellevels.tar.gz)

edit: uploaded a new tar with 1.00.29 data request files instead 1.00.28.

**Comment by taylor13** [comment]
this might be related to https://github.com/PCMDI/cmor/issues/430

**Comment by taylor13** [comment]
@tommibergman I have studied this issue further and have two questions: 
1. Do you get a similar error when you try writing bs550aer?  
2. Are you successful writing *any* of the variables in 6hrLev that are a function of alevel?

**Comment by tommibergman** [comment]
1. We cannot produce  the bs550aer from our model, so I have not tried. Also bs550aer is not a function of alevel, I think.
2. In the data I personally am working with, this is the only one which has this property. But @ufladrich in EC-Earth community has run to this problem also. 

See also our discussion on this is at EC-Earth/ece2cmor3#376

**Comment by goord** [comment]
Hi Tommi, I think the solution has been suggested in issue #430, you should use "ps1" for the instantaneous surface pressure for instantaneous model level fields.

**Comment by tommibergman** [comment]
I followed this but now I am faced with the problem of CMOR library not being able to work with 5 dimensions. But this is being solved in https://github.com/PCMDI/cmor/issues/430 . So I think this issue can be closed.

**Comment by mauzey1** [comment]
@tommibergman Now that https://github.com/PCMDI/cmor/issues/430 has been closed, I think we can close this issue.

**Comment by dongli** [comment]
I face this problem too when processing 6hrLev:
```
!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You defined variable 'ps' (table 6hrLev) with axis id 'time1' which is not part of this variable according to your table, it says: ( time latitude longitude )
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by dongli** [comment]
I think `ps1` and `ps2` (maybe) should be added to `CMIP6_formula_terms.json`. I could make a PR for this. Any suggestion?

**Comment by mauzey1** [comment]
@dongli `ps1` and `ps2` are part of `CMIP6_formula_terms.json`
https://github.com/PCMDI/cmip6-cmor-tables/blob/e47bd6d075ef2a7fd55ae34ff2832f56f14d1068/Tables/CMIP6_formula_terms.json#L164-L177

**Comment by dongli** [comment]
@mauzey1 Thanks! I found them.
