### ISSUE TITLE
standard_name of typeresidual in CMIP6_coordinate.json wrong?

### ISSUE THREAD

**Issue by jhardenberg** [PCMDI/cmip6-cmor-tables#232]
In `CMIP6_coordinate.json` the `standard_name` of `typeresidual` is set to "". Should that not be "area_type" ? (as for typenatgr, typepasture, typecrop etc.)

**Comment by taylor13** [comment]
Yes, @jhardenberg , I think you are correct. I am checking with @martinjuckes on whether this needs to be corrected upstream or if it is a problem with CMOR's table generator.

**Comment by taylor13** [comment]
@jhardenberg  I had forgotten that area_type can only be used for certain "area types".  As the CF conventions document says:
```
Some standard names (e.g. region and area_type) are used to indicate quantities
 which are permitted to take only certain standard values.
```
As @martinjuckes points out in https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/381 , typeresidual is not included in the list of valid values, so we can't give it standard name area_type.  
I'll close this, but feel free to reopen if there are unanswered questions about this.
