### ISSUE TITLE
Values of coordinate "basin" are no standard names

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmip6-cmor-tables#236]
Hi,
our QA annotates: values of `basin` are `atlantic_arctic_ocean` und `indian_pacific_ocean`.
However, there are `atlantic_ocean`, `indo_pacific_ocean` and `arctic_ocean` in the CF standard name table.
Will that be changed?
Best regards,
Fabi

**Comment by taylor13** [comment]
Hi Fabi,
I don't *think* there is a problem here.  The CF region list [here](http://cfconventions.org/Data/standardized-region-list/standardized-region-list.html) includes atlantic_arctic_ocean and indian_pacific_ocean as options.  You mentioned "standard name table", so maybe I'm confused.

**Comment by wachsylon** [comment]
Ok, sorry, problem solved. We had the wrong table for QA.
Thank you very much.
