### ISSUE TITLE
wrong generic_levels in CMIP6_Efx.json Header

### ISSUE THREAD

**Issue by tomaslovato** [PCMDI/cmip6-cmor-tables#240]
In the latest DReq 01.00.30 the entry 'generic_levels' in the table CMIP6_Efx.json still report old names

https://github.com/PCMDI/cmip6-cmor-tables/blob/d7f9eead12545f3daf1c6eaeb266433875f4cd3c/Tables/CMIP6_Efx.json#L12

and it should be correct as in the following

` "generic_levels": "alevhalf",`

**Comment by taylor13** [comment]
Yes. this should be corrected.  Given the related issue  https://github.com/PCMDI/cmip6-cmor-tables/issues/237 , we might want to check that this actually works.

**Comment by taylor13** [comment]
@mauzey1 What is the status of this?

**Comment by mauzey1** [comment]
@taylor13 I will get started on this.
