### ISSUE TITLE
Manually generating table_info MD5 hash

### ISSUE THREAD

**Issue by jhz0** [PCMDI/cmip6-cmor-tables#243]
I'm updating currently published files rather than reprocessing -- what string do I use to generate an MD5 hash for table_info?

**Comment by taylor13** [comment]
@doutriaux1 Can you respond?  I don't understand the question.

**Comment by mauzey1** [comment]
The MD5 hash for the table_info appears to be generated here...
https://github.com/PCMDI/cmor/blob/53ce99f72f0aebe3dca9b5d834a7b9f8f22d505b/Src/cmor_tables.c#L713

with this function
https://github.com/PCMDI/cmor/blob/53ce99f72f0aebe3dca9b5d834a7b9f8f22d505b/Src/cmor_md5.c#L289-L305

It looks like it is using the text of the whole table file to generate the hash.
@doutriaux1 @dnadeau4 Could you confirm?

**Comment by jhz0** [comment]
Thanks for your help. I've decided to use CMOR rather than a temporary manual process.
