### ISSUE TITLE
CMIP6_coordinate.json lambda550nm bounds correction

### ISSUE THREAD

**Issue by taylor13** [PCMDI/cmip6-cmor-tables#244]
@mauzey1  In CMIP6_coordinate.json, for variable lambda550nm replace

```
"must_have_bounds": "", 
```
with
```
"must_have_bounds": "no", 
```

**Comment by mauzey1** [comment]
@taylor13 
I have found 7 variables in `CMIP6_coordinate.json` that have `"must_have_bounds": ""`

- effectRadIc
- effectRadLi
- lambda550nm
- xant
- xgre
- yant
- ygre

What should they be set to?

**Comment by taylor13** [comment]
Sterling says that with the latest tables, he has no problem.  Do you know how must_have_bounds = "" gets handled in the code?  Is it interpreted as "no", or is it handled differently?

**Comment by mauzey1** [comment]
@taylor13 @sterlingbaldwin
https://github.com/PCMDI/cmor/blob/66cd98c178e16a848974fdccfaad2e7b908de4b7/Src/cmor_axes.c#L2260-L2265
CMOR will set `must_have_bounds` for an axis to 1 only if the `CMIP6_coordinate.json` entry has `"must_have_bounds": "yes"`.  `must_have_bounds` for an axis is 0 by default.

**Comment by taylor13** [comment]
Since it seems to treat "" the same as "no", perhaps we should modify the table to replace "" with "no" (just for better clarity).  What do you think?

**Comment by mauzey1** [comment]
The `must_have_bounds` value is coming from the `bounds` attribute in dreq.xml
```
<item altLabel="wavelength" axis="" bounds="" boundsValues="" coords="" description="Radiation wavelength used for monitoring aerosol properties" direction="" isGrid="" isIndex="" label="lambda550nm" positive="" requested="" standardName="radiation_wavelength" tables="" title="Radiation Wavelength 550 nanometers" tolRequested="" type="double" uid="dim:lambda550nm" units="nm" value="550.0"></item>
```
The convertXML.py script in xml-cmor3-database turns this into the `must_have_bounds` value in `CMIP6_coordinate.json`
https://github.com/PCMDI/xml-cmor3-database/blob/1fe99b3d0d21679503e7201a2e5be652adf656bb/src/convertXML.py#L438

**Comment by taylor13** [comment]
I have asked Martin to specify "yes" or "no" for the coordinates where they are currently not specified.  The change will then propagate to coordinate.json, so I'll close this.
