### ISSUE TITLE
Wrong long_name: depth, eta and eta2 in formula_entry

### ISSUE THREAD

**Issue by kjoti** [PCMDI/cmip6-cmor-tables#248]
In CMIP6_formula_terms.json.

```
        "depth": {
            "long_name": "Sea Floor Depth: formula term: thetao",
```

The last word of `long_name` (thetao) is wrong. The same is true for `eta` and `eta2`.

**Comment by taylor13** [comment]
@kjoti : Thanks for noticing this.  I have reviewed that table plus the coordinate table found a number of errors as summarized in https://github.com/PCMDI/cmip6-cmor-tables/issues/250

**Comment by taylor13** [comment]
I'll close this since it is being addressed in https://github.com/PCMDI/cmip6-cmor-tables/issues/250
