### ISSUE TITLE
Problems with parametric coordinates

### ISSUE THREAD

**Issue by taylor13** [PCMDI/cmip6-cmor-tables#250]
The definitions of a few of the (never-used, I think) parameteric coordinates and their formula terms are wrong or incomplete.  I think we should eliminate them for now.  Moreover there are a few other variables defined in the CMIP6_coordinate.json and CMIP6_formula_terms.json tables that should never get used (although they might appear in some of the "test" cases).  I think we should clean these up.  I suggest making the changes to those files listed below and then report which test cases fail.

I do not understand why some of these variables were defined (e.g., a_half, b_half, and ap_half), so will check with a few users I know and see if they need them.

We should also check whether when we define standard_names for some of the formula_terms, they actually show up in the output netcdf files.

Once these changes have been approved, we should probably check whether we can close issues https://github.com/PCMDI/cmip6-cmor-tables/issues/229, https://github.com/PCMDI/cmip6-cmor-tables/issues/245, and https://github.com/PCMDI/cmip6-cmor-tables/issues/248
```
formula_terms.json edits:

	remove z1
	remove z2
	remove b1
	remove b2
	remove href
	remove ztop
	remove a_half  ???
	remove b_half  ???
	remove ap_half  ???
	remove b1_half
	remove b2_half
	remove a_half_bnds
	remove b_half_bnds
	remove ap_half_bnds
	remove sigma
	remove sigma_bnds

	CHANGES in long_name:
	
	depth: "Sea Floor Depth"
	eta:  "Sea Surface Height"
	eta2: "Sea Surface Height"
	ps1: "Surface Air Pressure"
	ps2: "Surface Air Pressure"
	a:  "vertical coordinate formula term: a", 
	b: "vertical coordinate formula term: b", 
	ap: "vertical coordinate formula term: ap", 

	STANDARD_NAMES NEED TO BE ADDED FOR:
	ps, ps1, and ps2: air_pressure
	ptop:  air_pressure_at_top_of_atmosphere
	p0: reference_air_pressure_for_atmosphere_vertical_coordinate
	
	"units" should be corrected from "" to "m" for:
         depth_c, zlev, and zlev_bnds



coordinate.json edits:

	remove smooth_level
	remove smooth_level_half
	remove natural_log_pressure
	remove natural_log_pressure_half
	remove ocean_s
	remove ocean_double_sigma

	for "standard_hybrid_sigma_half, set z_bounds_factors = ""
	for "standard_sigma_half, set z_bounds_factors = ""
	for "alternate_hybrid_sigma_half, set z_bounds_factors = ""
	for "hybrid_height_half, set z_bounds_factors = ""
	for "ocean_sigma_z", set "z_factors": "sigma: lev eta: eta depth: depth depth_c: depth_c nsigma: nsigma zlev: zlev", 
        for "ocean_sigma_z", set "z_bounds_factors": "sigma: lev_bnds eta: eta depth: depth depth_c: depth_c nsigma: nsigma zlev: zlev_bnds", 


	DEFINE the following two coordinates:

        "ocean_sigma_half": {
            "standard_name": "ocean_sigma_coordinate", 
            "units": "", 
            "axis": "Z", 
            "long_name": "ocean sigma coordinate", 
            "climatology": "", 
            "formula": "z(n,k,j,i) = eta(n,j,i) + sigma(k)*(depth(j,i)+eta(n,j,i))", 
            "must_have_bounds": "no", 
            "out_name": "lev", 
            "positive": "up", 
            "requested": "", 
            "requested_bounds": "", 
            "stored_direction": "decreasing", 
            "tolerance": "", 
            "type": "", 
            "valid_max": "0.0", 
            "valid_min": "-1.0", 
            "value": "", 
            "z_bounds_factors": "", 
            "z_factors": "sigma: lev eta: eta depth: depth", 
            "bounds_values": "", 
            "generic_level_name": "olevhalf"
        }, 
        "ocean_sigma_z_half": {
            "standard_name": "ocean_sigma_z_coordinate", 
            "units": "", 
            "axis": "Z", 
            "long_name": "ocean sigma over z coordinate", 
            "climatology": "", 
            "formula": "for k <= nsigma: z(n,k,j,i) = eta(n,j,i) + sigma(k)*(min(depth_c,depth(j,i))+eta(n,j,i)) ; for k > nsigma: z(n,k,j,i) = zlev(k)", 
            "must_have_bounds": "no", 
            "out_name": "lev", 
            "positive": "", 
            "requested": "", 
            "requested_bounds": "", 
            "stored_direction": "", 
            "tolerance": "", 
            "type": "", 
            "valid_max": "", 
            "valid_min": "", 
            "value": "", 
            "z_bounds_factors": "", 
            "z_factors": "sigma: lev eta: eta depth: depth depth_c: depth_c nsigma: nsigma zlev: zlev", 
            "bounds_values": "", 
            "generic_level_name": "olevhalf"
}, 
```

**Comment by kjoti** [comment]
@taylor13 I guess `a_half` and `b_half` are introduced to handle the difference between `alevel` and `alevhalf` (i.e., existence or nonexistence of bounds).  If `a_half` and `b_half` are removed, the property `must_have_bounds` in hybrid-sigma coordinates needs to change from "yes" to "no" or bounds are always required even if half-level (just as CMIP5).

**Comment by taylor13** [comment]
@kjoti  You might be right, but I think CMOR considers "having bounds" as a characteristic of a coordinate variable, not the variables found in formula terms.  
The possibly important difference between `a` and `a_half` is that the "dimension" for one is `alevel` and for the other `alevhalf`.  Now if when writing half-level data, CMOR checks whether this "generic" vertical coordinate label for `a` is consistent with the generic vertical coordinate label for the hybrid_sigma_coordinate itself, then an error will be raised.  

I note that in defining a zfactor, the user passes the actual axis I.D. for the vertical dimension and the I.D.'s for the formula term, so I'm guessing it doesn't care what the generic names are.    We'll have to either examine the code (which is quite complex), or write a simple test code to determine CMOR's behavior.

**Comment by taylor13** [comment]
@ehogan @matthew-mizielinski:  When you write CMIP6 data on model half-levels (or for any other purpose), do you *need* "a_half", or do you simply define "a" (one of the hybrid_height formula terms)?   Variables requested on half-level include, for example, `phalf`, `rlu`, and `rsu`.  I'm trying to clean up the CMIP6_formula_terms.json file.  Thanks.

**Comment by taylor13** [comment]
In addition to the above, I think we should specify whether or not each coordinate "must_have_bounds" or not in coordinate.json.  The variables where this is currently unspecified (set to "") are:
effectRadIc, effectRadLc, xant, yant, xgre, ygre, lambda550nm.
I think some of these should be "yes" and some "no".  Will check with Martin J.
By the way, what is the "default" when left unspecified?

**Comment by ehogan** [comment]
@taylor13 we have `phalf_AERmon`, which has dimensions of [longitude latitude alevhalf time](https://github.com/PCMDI/cmip6-cmor-tables/blob/01.00.16/Tables/CMIP6_AERmon.json#L1726), produced using version 01.00.16 of the data request and CMOR v3.2.7 (we haven't been able to produce `phalf` using more recent versions due to a CMOR issue that I'll report shortly!). We define `a` and the output netCDF file contains a `lev` coordinate. So I don't think `a_half` is used. I hope that helps? :)

**Comment by ehogan** [comment]
Although I just found [this test](https://github.com/PCMDI/cmor/blob/11f7665d23e0780472e6d9d182a084d8b08f3ad6/Test/test_cmor_half_levels.py), which appears to use `a_half` in a call to `cmor.zfactor`.

**Comment by ehogan** [comment]
> We define `a`

We also define `b` and `orog` and use the [hybrid_height coordinate](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_coordinate.json#L703). The reason we haven't been able to produce `phalf_AERmon` recently is due to the addition of [hybrid_height_half](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_coordinate.json#L726) and changes to CMOR v3.3.3 to support this, which we need to take into account :)

However, the test I linked to in my previous comment would seem to suggest that `hybrid_height_half` would use `a_half` and `b_half`, except it doesn't (see the `formula` and `z_factors` attribute values for `hybrid_height_half`). Should it?

**Comment by taylor13** [comment]
@mauzey1 Regarding  [this test](https://github.com/PCMDI/cmor/blob/11f7665d23e0780472e6d9d182a084d8b08f3ad6/Test/test_cmor_half_levels.py) (thanks! @ehogan), could you please check whether replacing `a_half` and `b_half` with `a` and `b` changes the output?  These appear in:
```
cmor.zfactor(zaxis_id=ilev_half, zfactor_name='b_half', axis_ids=[ilev_half, ],
             zfactor_values=common.b_coeff)
print("b 1/2")
cmor.zfactor(zaxis_id=ilev_half, zfactor_name='a_half', axis_ids=[ilev_half, ],
             zfactor_values=common.a_coeff)
print("a 1/2")
```
Also are there any other test codes that include `a_half`, `b_half`, `ap_half`, `a_half_bnds`, `b_half_bnds`, or `ap_half_bnds`?

**Comment by taylor13** [comment]
@ehogan To answer your question ...
Since `a_half` has `"out_name": "a"`, you would create the same netCDF variable by defining z-factor `a_half` or `a`.   That's why I don't think we need `a_half` and that's why `z_factors` and `formula` contain `a`, not `a_half`.
The only difference between `a_half` and `a` is that `a_half` has a dimension `alevhalf`, whereas a has a dimension `alevel`.  But I don't think CMOR cares about this.  We'll see if I'm right when @mauzey1 changes the above "test" code.

**Comment by taylor13** [comment]
While we're cleaning up the coordinate.json file, we should consider removing  `location` and `plev7`, as discussed in https://github.com/PCMDI/cmip6-cmor-tables/issues/155 and https://github.com/PCMDI/cmip6-cmor-tables/issues/172

**Comment by kjoti** [comment]
@taylor13 
> so I'm guessing it doesn't care what the generic names are.

The current CMOR implementation cares about the generic names. Please look at line 1597 in cmor_variable.c.

At this if-statement, `generic_level_name` in `refvar` and in `axes` are compared. If they do not match, it is considered an error. I think this check is too strict and can be relaxed or removed. If this check is removed, both `a_half` and `b_half` will be unnecessary.

First of all, we should consider whether it is good or bad that `generic_level_name` is not only in `cmor_axis_def_t` but also in `cmor_var_def_t`.

``` c:cmor.h
typedef struct cmor_axis_def_ {
    ...(snip)...
    char generic_level_name[CMOR_MAX_STRING];
} cmor_axis_def_t;

typedef struct cmor_variable_def_ {
    ...(snip)...
    char generic_level_name[CMOR_MAX_STRING];
} cmor_var_def_t;
```

**Comment by ehogan** [comment]
@kjoti @taylor13 that bit of code is what is stopping us from producing `phalf_AERmon`:

```
C Traceback:
! In function: cmor_variable
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You defined variable 'phalf' (table AERmon) with axis id 'hybrid_height', the 
! variable calls for a generic axis of type 'alevhalf' according to your table, the axis 
! you are providing is of generic type 'alevel'
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by kjoti** [comment]
@ehogan @taylor13 
You must use `hybrid_height_half` rather than `hybrid_height`.  This is a matter of axes, not formula terms.

For `phalf`, current CMOR requires using `hybrid_heigt_half` as the axis and using `a_half` and `b_half` as the formula terms (zfactor).

The point of this issue is that formula terms should not care about `alevel` or `alevhalf` and that `a_half` and `b_half` are needless.

**Comment by ehogan** [comment]
Apologies @kjoti, I misread your original comment; I thought you were suggesting removing the check completely; I was trying (and failing!) to make the point that the check would still be required for the axes. So I think we're on the same page :)

**Comment by taylor13** [comment]
I agree that for variable phalf, you must define and point to a hybrid_height_half axis .  I think that will eliminate the error shown in  https://github.com/PCMDI/cmip6-cmor-tables/issues/250#issuecomment-492959188

However, I've not seen a test case that says you can't define a and b (with axis index passed to zfactor pointing to the same hybrid_height_half axis) rather than defining a_half and b_half.  That should be revealed after doing the test requested in https://github.com/PCMDI/cmip6-cmor-tables/issues/250#issuecomment-492333117

**Comment by mauzey1** [comment]
@taylor13 When I change `a_half` and `b_half` to `a` and `b` in [test_cmor_half_levels.py](https://github.com/PCMDI/cmor/blob/11f7665d23e0780472e6d9d182a084d8b08f3ad6/Test/test_cmor_half_levels.py), the test throws this error:
```
!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You defined variable 'b' (table Amon) with axis id 'standard_hybrid_sigma_half', the variable calls for a generic axis of type 'alevel' according to your table, the axis you are providing is of generic type 'alevhalf'
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by wachsylon** [comment]
> However, I've not seen a test case that says you can't define a and b (with axis index passed to zfactor pointing to the same hybrid_height_half axis) rather than defining a_half and b_half. That should be revealed after doing the test requested in #250 (comment)

I agree that it is a good idea to enable to use a and b instead of a_half and b_half. It would shorten the code in CMOR applications (at least in one).

Regarding the rest of the clean up plan: I cannot see any problem.

**Comment by taylor13** [comment]
So as not to hold things up any longer, let's, for now, implement all the changes listed in https://github.com/PCMDI/cmip6-cmor-tables/issues/250#issue-442470684 *except* the ones with the "???" .

**Comment by taylor13** [comment]
yes, I think so.

**Comment by mauzey1** [comment]
@taylor13 I think everything has been done for this issue.  Can we close it?

**Comment by taylor13** [comment]
Yes, I think so.   Thanks for checking.
