### ISSUE TITLE
Dimension inconsistency for olevhalf

### ISSUE THREAD

**Issue by clintseinen** [PCMDI/cmip6-cmor-tables#252]
My colleagues (@ashao) and I have recently come across an interesting problem when attempting to use [cmor](https://github.com/PCMDI/cmor) 3.4.0's `python` interface, along with commit `cbad798` of this repo, to convert some data in the `Oclim` table. 

When we attempt to run 
```python
cmor.load_table("CMIP6_Oclim.json")
```
we get the following error:
```
C Traceback:
! In function: cmor_set_var_def_att
! called from: cmor_set_variable_entry
! called from: cmor_load_table_internal
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Reading table Oclim: axis name: 'olevhalf' for variable: 'zhalfo' is not defined in table. Table defines dimensions: 'longitude latitude olevhalf time2' for this variable
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```
We were previously using commit `3ebb6d4d2b7bac36fbd1d2ca545b9d17efd2a34c` for the cmor tables, and didn't see this problem. Between these commits there doesn't seem to be many differences in the `CMIP6_Oclim.json` table, but there does seem to be a major difference in `CMIP6_coordinates.json` that could affect this; namely, the addition of `depth_coord_half` and removal of `olevhalf` entirely. Looking at issue #237, and merge #241, it looks like this was on purpose, but is it possible that something else should've been changed along with this? Or could this be a problem on our end? 

I should also note that we aren't even attempting to convert `zhalfo`, but were instead trying to initialize `cmor` before converting `diftrelo2d`. Additionally, prior to this, we first initialize `cmor` with 
```python
cmor.setup(inpath='path/to/cmip6-cmor-tables/Tables',netcdf_file_action=cmor.CMOR_REPLACE_4)
```

**Comment by mauzey1** [comment]
@clintseinen 
The changes for `olevhalf` were also applied to CMOR.
Issue: https://github.com/PCMDI/cmor/issues/457
PR: https://github.com/PCMDI/cmor/pull/460
These changes are currently in the nightly build of CMOR, but not in the current stable 3.4.0.  The next stable release of CMOR (3.5.0) will have these changes.  We plan to release 3.5.0 this month.

**Comment by clintseinen** [comment]
Great! Thanks for letting me know @mauzey1 ! I'll be keeping an eye out for the `3.5.0` release

**Comment by clintseinen** [comment]
@mauzey1 I can confirm that after updating `cmor` to `3.5.0`, I was able to convert data from the `Oclim` table.
