### ISSUE TITLE
Issue with Ofx variable 'basin'

### ISSUE THREAD

**Issue by RosalynHatcher** [PCMDI/cmip6-cmor-tables#256]
I notice that the CMOR tables dictate that the Ofx variable `basin` with `standard_name = "region"` uses `flag_values`/`flag_meanings` to indicate the region names.  However, this doesn't fit with CF which states that a variable with the `standard_name = "region"` should contain values from the standard name region list.  

So CMIP6 files with the `basin` variable will currently fail the CF Checker.

**Comment by taylor13** [comment]
@RosalynHatcher All of the values are in fact in the standard name region list at http://cfconventions.org/Data/cf-standard-names/docs/standardized-region-names.html .  It is therefore somewhat redundant to include them as flag_values and flag_meanings, but I don't think it should be illegal.  

Does the checker throw a warning or an error?

The basin names in Ofx are:
```
global_land 
southern_ocean 
atlantic_ocean 
pacific_ocean 
arctic_ocean 
indian_ocean 
mediterranean_sea 
black_sea 
hudson_bay 
baltic_sea 
red_sea
```

**Comment by RosalynHatcher** [comment]
@taylor13: Currently using `flag_values`/`flag_meanings` to indicate region_names is not allowed by CF.  There is a proposal for this to be allowed but it has not made it into the conventions yet, so the conformance checker will flag this as an error currently.

**Comment by taylor13** [comment]
@RosalynHatcher: Sorry, I can't seem to find in the convention where it says flag_values/flag_meanings may not be used to describe geographical regions when the ``standard_name='region'``.  What I find is the following:
```
We recommend that the names be chosen from the list of standardized region names 
whenever possible. To indicate that the label values are standardized the variable that 
contains the labels must be given the standard_name attribute with the value region.
```
I don't think this precludes also defining flag_values/flag_meanings, although as I mentioned earlier the information would be redundant.

**Comment by RosalynHatcher** [comment]
@taylor13:  That is the section.  The last statement indicating that if a variable has a standard_name with the value region then it is a label variable with values from the standardized list.  The convention does need clarification which is what the proposal [here](https://cf-trac.llnl.gov/trac/ticket/151) was meant to do but hasn't yet been adopted.  I will try and get the conversation restarted on this proposal.

**Comment by taylor13** [comment]
@RosalynHatcher Would you agree that example 3.4 in [section 3.5](http://cfconventions.org/cf-conventions/cf-conventions.html#flags) of the draft conventions version 1.8 will explicitly permits the use of ``region`` in the way it is used in CMIP6?  If so, I assume the checker will be adapted to this change?  So, do you agree that once V1.8 is released, we can close this issue?

**Comment by RosalynHatcher** [comment]
@taylor13: Yes I agree once v1.8 is released this issue can be closed. I will raise an issue for the cf-checker to be updated in line with this.

**Comment by taylor13** [comment]
CF versions 1.8 has now been released, so consistent with https://github.com/PCMDI/cmip6-cmor-tables/issues/256#issuecomment-556271636 , I'm closing this issue.
