### ISSUE TITLE
No alevel in bs550aer

### ISSUE THREAD

**Issue by kjoti** [PCMDI/cmip6-cmor-tables#257]
`bs550aer` in 6hrLev does not have `alevel` dimension.

At the commit f346afdb (tag: 6.1.22), `alevel` was removed.
Is it intended?

**Comment by taylor13** [comment]
@kjoti -- That update was at time time consistent with the data request.  Currently the data request indicates that for ``bs550aer`` the dimensions should be:
```
"dimensions": "longitude latitude time1 lambda550nm scatter180"
```
So there is no "level" coordinate, but a ``scatter180`` dimension has been added.  If you think this might be a mistake (and it might be), please submit an issue at: https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues .  

thanks for helping with this.

**Comment by taylor13** [comment]
This issue has now been correctly raised at https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/399, so I will close it here.
