### ISSUE TITLE
New CMIP6 CV update strategy

### ISSUE THREAD

**Issue by mauzey1** [PCMDI/cmip6-cmor-tables#261]
Recent issues caused by changes to CMIP6_CV.json being committed directly to the `master` branch (#259 and https://github.com/PCMDI/cmor/issues/543) show a need for a new way to update this file.

I propose having a branch called `develop` where changes to CMIP6_CV.json will be pushed to daily.  We can merge `develop` into `master` when all tests are passing.  If they fail then we can fix the issue upstream before updating the `develop` branch.

@sterlingbaldwin @durack1 Do you have any other ideas for improving the update of CMIP6_CV.json?

On a related note, the scripts that are used for updating CMIP6_CV.json are located in the [CMOR repo](https://github.com/PCMDI/cmor/tree/master/scripts).  I think they should be moved to this repo instead.

**Comment by durack1** [comment]
Thanks @mauzey1 I think this is a good interim step and buys considerable time before changes can be made in PCMDI/cmor#543

**Comment by mauzey1** [comment]
The `develop` branch has been set up to receive changes to CMIP6_CV.json.  We will see how well this works
