### ISSUE TITLE
CMIP6_CV.json does not appear to be updating

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmip6-cmor-tables#267]
@mauzey1 it seems that [`CMIP6_CV.json`](https://github.com/PCMDI/cmip6-cmor-tables/commit/3fafdc876e363877c41a6f40e05f6d377fcaada2) is not updating nightly, with the last change back on the 4th October 2019 (version: 6.2.39.0). We've had a number of recent updates which have brought us up to [6.2.39.6](https://github.com/WCRP-CMIP/CMIP6_CVs/commit/0ba774adeac123006fbc6aec82c470c59b3bf911), the latest change was made on the 22nd October 2019.

Can you take a peek at this please?

**Comment by mauzey1** [comment]
@durack1 I was trying to figure that out yesterday.  I tried manually running the script that the cronjob is meant to perform and it was able to create a commit at 4216364b3affa9ef396f12b670dd7fcdd4efc6b7.  The cronjob wasn't working due to not configuring the time correctly.  The cronjob has been fixed since there was a commit pushed last midnight at e0090daa695a35badefdd5752bed97b18b3f55da.

What I am trying to figure out now is why the CircleCI tests didn't run when the commits were pushed.

**Comment by durack1** [comment]
@mauzey1 thanks for getting to this so quickly!

**Comment by durack1** [comment]
@mauzey1 it seems we're still behind, I have made a couple of updates to the CVs today bring us up to 6.2.39.11 but we're stuck at 6.2.39.0

**Comment by durack1** [comment]
@mauzey1 it seems we're back up to date with [`"CV_collection_version":"6.2.39.14"`](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json#L37), I assume this happened automagically?

If so, are you happy for this to be closed?

**Comment by mauzey1** [comment]
@durack1 I got the cronjob working to update the `develop` branch, and got the CircleCI tests working again to check the tables.  Currently, I need to manually merge `develop` into `master` when changes are pushed by the cronjob.  At some point, I would like to find a way for CircleCI to automatically merge `develop` changes into `master` when tests pass.  However, I think we can close this issue.

**Comment by durack1** [comment]
@mauzey1 great. So there will still be some involvement from you the next time changes are made to the CMIP6_CVs? Do you need to know about this, or watch the repo, or are you getting prompted by the cronjob?

I'll close this anyway

**Comment by mauzey1** [comment]
@durack1 I currently just check the repo if new changes are pushed to `develop`.
