### ISSUE TITLE
CMIP6_Oclim.json Header should include olevhalf as well (01.00.31)

### ISSUE THREAD

**Issue by valeriupredoi** [PCMDI/cmip6-cmor-tables#269]
Hey guys, the `"Header"` dictionary for `CMIP6_Oclim.json` in `01.00.31` contains the following for generic levels:
```
"generic_levels": "olevel",
```
but since the olevhalf is not defined as a main coordinate in `CMIP6_coordinates.json` anymore and is in turn a generic level that header should probably be
```
"generic_levels": "olevel olevhalf",
```
...just like in `CMIP6_Omon.json`

Cheers much! :beer:

**Comment by durack1** [comment]
@valeriupredoi thanks for this, we'll also need to check the `CMIP6_Oday`, `*Odec`, `*Ofx` and `*Oyr` tables as well to ensure consistency

**Comment by valeriupredoi** [comment]
Hi @durack1 I did check those wrt `olevhalf` and they seemed OK to me, but am not a pro :grin: They ran fine through our automated tests in ESMValTool 
Cheers :beer:

**Comment by taylor13** [comment]
Just checked the ocean tables, and only Omon and Oclim have any instances of olevhalf, so as indicated above, please add olevhalf as a generic_level to Oclim.

**Comment by durack1** [comment]
@taylor13 thanks for this

**Comment by mauzey1** [comment]
@durack1 @taylor13 
Should we also remove generic_levels if they are not present in the dimensions of variables in a table?  For example, [CMIP6_6hrLev.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/989a32d9ee326a8eddd2409e090df0cdffa3bf60/Tables/CMIP6_6hrLev.json#L2-L15) has `"generic_levels": "alevel alevhalf"` but none of the variables in the table have `alevhalf` in their dimensions lists.
