### ISSUE TITLE
CMIP6 Volcello is its own cell measure.

### ISSUE THREAD

**Issue by ledm** [PCMDI/cmip6-cmor-tables#273]
In the CMIP6 tables, `CMIP6_Oyr.json`, `CMIP6_Omon.json`, `CMIP6_Odec.json`, and `CMIP6_Ofx.json`, the cell volume `volcello` is set to be it's own cell measure.

ie, in  `CMIP6_Oyr.json`:
```
        "volcello": {
            "frequency": "yr", 
            "modeling_realm": "ocean", 
            "standard_name": "ocean_volume", 
            "units": "m3", 
            "cell_methods": "area: mean where sea time: mean", 
            "cell_measures": "area: areacello volume: volcello", 
            "long_name": "Ocean Grid-Cell Volume", 
            "comment": "grid-cell volume ca. 2000.", 
            "dimensions": "longitude latitude olevel time", 
            "out_name": "volcello", 
            "type": "real", 
            "positive": "", 
            "valid_min": "", 
            "valid_max": "", 
            "ok_min_mean_abs": "", 
            "ok_max_mean_abs": ""
        },
```

This seems like a strange choice and have caused some trouble for Iris loading these files. We have a discussion in the iris issues page, here:
https://github.com/SciTools/iris/issues/3544

**Comment by durack1** [comment]
@taylor13 can you take a peek at this, we could have similar issues with other area/volume variables

**Comment by taylor13** [comment]
This issue has been raised before as [issue 216](https://github.com/PCMDI/cmip6-cmor-tables/pull/216).   If something is to be done, it must be done in the data request. Then it will propagate to the CMOR tables.  On the github data-request repository, I reported this as [issue 394](https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/394).   I see someone has already reported the iris problem there, but I will reinforce that with a comment.

**Comment by ledm** [comment]
Thanks @taylor13, @durack1.
