### ISSUE TITLE
"external_variables" missing from "required_global_attributes" in CMIP6_CV.json

### ISSUE THREAD

**Issue by mauzey1** [PCMDI/cmip6-cmor-tables#278]
@durack1 
The attribute `external_variables`is missing from `required_global_attributes` in CMIP6_CV.json.  This has prevented PrePARE from detecting the absence of `external_variables` in NetCDF files.

This is related to the issues in https://github.com/PCMDI/cmor/issues/541.

**Comment by durack1** [comment]
@mauzey1 I assume the current content is copied from [WCRP-CMIP/CMIP6_CVs/CMIP6_required_global_attributes.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_required_global_attributes.json)? If yes, then I will open a new issue in the CMIP6_CVs and get that fixed today

**Comment by mauzey1** [comment]
@durack1 Yes, the content of `required_global_attributes` is copied from that file.

**Comment by durack1** [comment]
@mauzey1 this should be fixed upstream, so the cronjob should pull across this new entry if you don't manually grab it before then, I closed with the PR https://github.com/WCRP-CMIP/CMIP6_CVs/pull/850
