### ISSUE TITLE
Clarification needed between "alev1" and "alevel" coordinates

### ISSUE THREAD

**Issue by agstephens** [PCMDI/cmip6-cmor-tables#30]
I have noted that many of the CMIP6 tables include reference to an `alevel` coordinate that does not exist in the `CMIP6_coordinate.json`. This search shows the occurrences of `alevel`:

https://github.com/PCMDI/cmip6-cmor-tables/search?utf8=%E2%9C%93&q=%22alevel%22

In the following coordinate JSON file there is a definition of the coordinate `alev1`:

https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_coordinate.json

The `alev1` coordinate does not appear to be referenced by any variable definitions - see the following search results:

https://github.com/PCMDI/cmip6-cmor-tables/search?utf8=%E2%9C%93&q=%22alev1%22

I am guessing that the definition of `alev1` in the `CMIP6_coordinate.json` file should be changed to `alevel`. 

Please have a look. Thanks, Ag

**Comment by dnadeau4** [comment]
`alevel` is not a `real` coordinate (dimension).  


See the following example [test_python_jamie_6.py](https://github.com/PCMDI/cmor/blob/master/Test/test_python_jamie_6.py).  In this example  axis alevel is declared as `hybrid_height` which is defined int he [CMIP6_coordinates.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_coordinate.json#L600-L621) file.  

This `alevel` dimension also contains `formula terms` defined in [CMIP6_formula_terms.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_formula_terms.json)

**Comment by agstephens** [comment]
Hi @dnadeau4, Having discussed it with my colleagues we now understand what is going on here. Thanks for your response. Closing this one now :-)
