### ISSUE TITLE
rsdt daily

### ISSUE THREAD

**Issue by oligan** [PCMDI/cmip6-cmor-tables#317]
I'm surprised rsdt is not required on a daily basis in historical run (r1 is sufficient as rsdt is the same for all members). It would be useful to have this variable in a future release for the record.

**Comment by taylor13** [comment]
This issue has also been raised at https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/407, which is the best place to address it, so I'll close it here.
