### ISSUE TITLE
CMIP6_CV.json cron seems to have failed

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmip6-cmor-tables#324]
I just took a peek at [CMIP6_CV.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json) which still seems to be at version 6.2.53.14, when yesterday afternoon it was bumped to [6.2.54.1](https://github.com/WCRP-CMIP/CMIP6_CVs).

It seems the cron job has failed again.

@taylor13 @mauzey1

**Comment by mauzey1** [comment]
@durack1 The previous machine used for the cron job is down so I moved it to another machine.  The CMIP6 CV updates have been merged.
