### ISSUE TITLE
Update to CMIP6 Data Request 01.00.33

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmip6-cmor-tables#329]
The CMIP6 Data Request 01.00.33 has been released:
```
From: "Juckes, Martin (STFC,RAL,RALSP)"
Date: Friday, November 6, 2020 at 10:18 AM
To: WIP List, "CMIP6-DATAREQUEST"
Cc: "CMIP6-ENDORSEDMIPS-COCHAIRS", "CMIP6-MODELGROUPS-SCI"
Subject: CMIP6 Data Request 01.00.33

Dear All, 

Version 01.00.33 of the Data Request is now available.

•	Release notes: https://cmip6dr.github.io/Data_Request_Home/Releases/drq_release_01_00_33.html 
•	Package: https://pypi.org/project/dreqPy/1.0.33
•	Repository: http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/tags/01.00.33

The Data Request web pages are migrating from the current site to github. This migration is in progress, and, for now, the home page is https://cmip6dr.github.io/Data_Request_Home/ . 

This release adds some experiments and makes corrections to long names of two variables.

Regards,
Martin
```
This issue and subsequent pull request will allow #208 and #307 to also be closed (as these were both related to earlier CMIP6 Data Request releases - having said that, any other tweaks may still need to be applied)

**Comment by mauzey1** [comment]
@durack1 @martinjuckes
There is surprisingly very little change to the tables for this data request.  It seems most of the changes were for CMIP6_CV.json, which is updated outside of releases.  The changes for `tntrl27` and `tntrs27` didn't affect the tables since they already had the correct definitions.

I will generate a PR shortly for review.

**Comment by durack1** [comment]
The major update to the CMIP6 Data Request was the addition of new experiments, which are already included in the CMIP6_CV.json as you note, these new experiments just use already existing variables, so not much of a change that propagates to this repo

**Comment by mauzey1** [comment]
@durack1 The tables have now been updated and a release has been created: https://github.com/PCMDI/cmip6-cmor-tables/releases/tag/6.9.33
