### ISSUE TITLE
Renaming default branch to 'main' on October 11, 2023

### ISSUE THREAD

**Issue by mauzey1** [PCMDI/cmip6-cmor-tables#407]
Similar to the proposed change for CMOR (https://github.com/PCMDI/cmor/issues/712), I plan to change the name of the default branch of this repo from `master` to `main` on Wednesday, October 11.

**Comment by durack1** [comment]
Fixed in https://github.com/PCMDI/cmip6-cmor-tables/commit/2b94d5a6db25451e3aa92492c029477c0187b9d6 closing
