### ISSUE TITLE
Value of baseURL in CMIP6_grids.json needs updating/removing

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmip6-cmor-tables#41]
The value of 
```
"baseURL": "http://cmip-pcmdi.llnl.gov/CMIP6/dataLocation",
```
[Found here](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_grids.json#L4)

Points to a non-existent URL, when the URL remapping is finalised on the 20th March 2017 it would be worthwhile changing this, or removing the spurious entry

@taylor13 @dnadeau4 @sashakames we need to discuss this

**Comment by dnadeau4** [comment]
That is old metadata from `cmor2`.  I removed it in all other tables and we decided that having a broken link in every file was not worth it.  As you can see `CMIP6_grids.json` is a hack from CMIP5 tables. :smirk:

**Comment by durack1** [comment]
@dnadeau4 well time that it also gets scrubbed from the `CMIP6_grids.json` then too?

**Comment by dnadeau4** [comment]
Done!  Will be in the next version of the tables...

**Comment by durack1** [comment]
@dnadeau4 wanna link this to the PR that solves the issue and then close?

**Comment by dnadeau4** [comment]
PR: https://github.com/PCMDI/cmip6-cmor-tables/pull/51
