### ISSUE TITLE
HighResMIP start date incorrect

### ISSUE THREAD

**Issue by jonseddon** [PCMDI/cmip6-cmor-tables#43]
Hi,

In CMIP6_CV.json, the start year for the several HighResMIP experiments is incorrect. The affected experiments are:

highresSST-present
hist-1950
highresSST-4co2
highresSST-LAI
highresSST-smoothed
highresSST-p4K

In each of these the start year is listed as 1951, but it should be 1950.

Is this the correct place to report this, or where should I report this?

Thanks,

Jon

**Comment by dnadeau4** [comment]
@jonseddon I linked this issue with the WCRP-CMIP/CMIP6_CVs#263.  This is where the control vocabulary files are maintained.  CMIP6_CV.json is a merge of all the CVs file for CMOR3 .

**Comment by jonseddon** [comment]
Thanks @dnadeau4  for linking to the other repository. I can see now that the changes have been made in the controlled vocabulary and will be pulled through to here at the next release. Thanks for your help!
