### ISSUE TITLE
Sort CMIP6_CV.json entries to maintain upstream consistency

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmip6-cmor-tables#49]
@dnadeau4 I was checking the [`CMIP6_CV.json`](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json#L64-L93) values in this repo against [their upstream version](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_institution_id.json#L3-L32) and noted that you are not sorting (like in the upstream versions).

This made me think that you were missing values, which isn't the case.

Would it be easy to sort the outputs? This will also make debugging easier..

It's as easy as adding some additional keywords, this is what I do for the upstream:
```python
json.dump(jsonDict, fH, ensure_ascii=True, sort_keys=True, indent=4, separators=(',', ':'), encoding="utf-8")
```

**Comment by dnadeau4** [comment]
You wont `sort_keys=True` or `object_pairs_hook=OrderedDict` to keep the original order?

**Comment by durack1** [comment]
@dnadeau4 the original files are written with `sort_keys=True` so that should maintain consistency

**Comment by dnadeau4** [comment]
How is that?
[CMIP6_CV.json.txt](https://github.com/PCMDI/cmip6-cmor-tables/files/904192/CMIP6_CV.json.txt)

**Comment by dnadeau4** [comment]
I think @taylor13 wanted the experiment_id at the end...

**Comment by durack1** [comment]
@dnadeau4 having `version_metadata` at the end makes sense to me..

**Comment by dnadeau4** [comment]
I used to have `required_global_attributes` at the top which was easy to find.  And I had my extraneous check at the end.  Now it is confusing...

**Comment by dnadeau4** [comment]
What about this one?  I kept your order for each file but create my own order for the main CV section.
[CMIP6_CV.json.txt](https://github.com/PCMDI/cmip6-cmor-tables/files/904199/CMIP6_CV.json.txt)

**Comment by durack1** [comment]
@dnadeau4 yeah that's fine, I just wanted each of the sub-entries to maintain sort order, otherwise it's too hard to figure out what is missing or isn't

**Comment by dnadeau4** [comment]
Ok, let's keep it this way...

**Comment by taylor13** [comment]
@dnadeau4 

I still think it is easier for users to browse (if that's iimportant) if the very long lists are last:  institution_id, source_id, and experiment_id.   (We expect both source_id and institution_id to grow in size.)

**Comment by dnadeau4** [comment]
@taylor13 

Can you re-order as you feel is right?  (Computers don't really care...)

I read all WCRP in the followin order and then add my 1 line regular expression at the end of the file.

```python
        "CMIP6_required_global_attributes.json",
        "CMIP6_activity_id.json",
        "CMIP6_institution_id.json",
        "CMIP6_source_id.json",
        "CMIP6_source_type.json",
        "CMIP6_frequency.json",
        "CMIP6_grid_label.json",
        "CMIP6_nominal_resolution.json",
        "CMIP6_realm.json",
        "CMIP6_table_id.json",
        "CMIP6_license.json",
        "mip_era.json",
        "CMIP6_sub_experiment_id.json",
        "CMIP6_experiment_id.json"
```

And I add this.
```python
        "product":[
            "model-output"
        ],
        "tracking_id":[
            "hdl:21.14100/.*"
        ],
        "further_info_url":[
            "http://furtherinfo.es-doc.org/[[:alpha:]]\\{1,\\}"
        ],
        "realization_index":[
            "^\\[\\{0,\\}[[:digit:]]\\{1,\\}\\]\\{0,\\}$"
        ],
        "variant_label":[
            "r[[:digit:]]\\{1,\\}i[[:digit:]]\\{1,\\}p[[:digit:]]\\{1,\\}f[[:digit:]]\\{1,\\}$"
        ],
        "data_specs_version":[
            "^[[:digit:]]\\{2,2\\}\\.[[:digit:]]\\{2,2\\}\\.[[:digit:]]\\{2,2\\}$"
        ],
        "Conventions":[
            "^CF-1.7 CMIP-6.0\\( UGRID-1.0\\)\\{0,\\}$"
        ],
        "forcing_index":[
            "^\\[\\{0,\\}[[:digit:]]\\{1,\\}\\]\\{0,\\}$"
        ],
        "initialization_index":[
            "^\\[\\{0,\\}[[:digit:]]\\{1,\\}\\]\\{0,\\}$"
        ],
        "physics_index":[
            "^\\[\\{0,\\}[[:digit:]]\\{1,\\}\\]\\{0,\\}$"
        ]
```

**Comment by dnadeau4** [comment]
@taylor13 @durack1 do you care about the order of information in the CMIP6_CV.json file?

**Comment by dnadeau4** [comment]
@durack1 can we close?

**Comment by durack1** [comment]
@dnadeau4 yep looks good to me, we can always revisit in the future if required
