### ISSUE TITLE
Update CMIP6_CV.json source_id entry

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmip6-cmor-tables#52]
@dnadeau4 we suggest that the `source_id` entries in [cmip6-cmor-tables/CMIP6_CV.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json#L95-L127) should be simplified to be a concatenation of the `source_id` fields, so: `label`,`release_year`, and the `description` entries from `atmos`, `ocean`, `seaIce`, `land`, `aerosol`, `atmosChem`, `ocnBgchem` and `landIce`. This then looks like:
```
"ACCESS-1-0":{
    "activity_participation":[
        "CMIP"
    ],
    "cohort":[
        "CMIP5"
    ],
    "institution_id":[
        "CSIRO-BOM"
    ],
    "source":"ACCESS 1.0 (2011):\n
             atmos: HadGAM2 (r1.1; N96, 192 x 145 longitude/latitude; 38 levels; top level 39255 m);\n
             ocean: ACCESS-OM (MOM4p1; tripolar primarily 1deg, 360 x 300 longitude/latitude; 50 levels; top grid cell 0-10 m);\n
             seaIce: CICE4.1;\n
             land: MOSES2.2;\n
             aerosol: CLASSIC (v1.0);\n
             atmosChem: None;\n
             ocnBgchem: None;\n
             landIce: None;"
},
```
This requires the `source_id` entries obtained from the CMIP6_CVs repo [CMIP6_CVs/CMIP6_source_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L3-L51) to be reformatted to the above, which requires only editing the information contained in the `cmip6-cmor_tables/CMIP6_CV.json` file RATHER than changes within the `cmor` code itself. This enables a pythonic tweak, rather than having to deal with json nested dictionaries in C. The resultant `source` field will then be written to the CMOR-written netcdf file as a `source` global attribute

For reference the source_id that this information has been harvested from can be seen at https://github.com/WCRP-CMIP/CMIP6_CVs/issues/264#issuecomment-293993334

**Comment by durack1** [comment]
@taylor13 pinging you here. This refers to the Table Note 13 in the google doc: https://goo.gl/v1drZl

**Comment by dnadeau4** [comment]
@durack1 can we close this?

**Comment by durack1** [comment]
@dnadeau4 yes I believe this is ok, as [`source_id`](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json#L109) in the current `CMIP6_CV.json` looks great

**Comment by taylor13** [comment]
if what Paul says is true, then yes, this issue can be closed.

**Comment by durack1** [comment]
@taylor13 alternative facts..
