### ISSUE TITLE
Fix introduced cell_methods problem with 01.00.06

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmip6-cmor-tables#53]
see PCMDI/cmor#157

A change in [PCMDI/cmip6-cmor-tables#0ad7689](https://github.com/PCMDI/cmip6-cmor-tables/commit/0ad7689eec872228cd23ed33aa85c5e6349bc7ba), with the `01.00.06` update (PCMDI/cmip6-cmor-tables#50) `cell_methods` went from:
```
FROM:
21 "cell_methods": "time: mean",
TO:
21 "cell_methods": "area: time: mean ",
...
22 "cell_measures": "area: areacella",
```
This seems to be a weird hybrid of the `cell_methods` and `cell_measures` and a clear error in the table update

**Comment by dnadeau4** [comment]
@durack1  This is a valid `cell_methods` It means that "area and time" are averaged.

**Comment by durack1** [comment]
@dnadeau4 no problem, I was hitting issues back trying to generate the updated AMIP data.. I managed to get things working, so consequently this issue is no longer applicable..
