### ISSUE TITLE
CMIP6_CV.json in this repository differs from the CMIP6_CV.json file in the cmor repository

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmip6-cmor-tables#58]
The [CMIP6_CV.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json) file in this repository was updated 24 days ago and is different to the [CMIP6_CV.json](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_CV.json) file in the https://github.com/PCMDI/cmor repository, which was updated 15 days ago.

We are using this repository to update our local copies of the MIP tables as I was under the impression that this repository was the definitive place to obtain the MIP tables from. Therefore, would it be possible for the CMIP6_CV.json file in this repository to also be the definitive version, please?

(I found an issue using the version of the CMIP6_CV.json file from this repository that was resolved when using the CMIP6_CV.json file from the cmor repository)

**Comment by dnadeau4** [comment]
I tried to update it, but LLNL block `github` for security reasons.   We finally got the links unblocked last Monday.  

>>I have unblocked the raw.githubusercontent.com
>>Cyber Security Operations Center  (CSOC)

I will update the file today or tomorrow.

**Comment by dnadeau4** [comment]
@durack1 have changed something in `realm`.  My tests are passing.  I also changed `source`.

**Comment by dnadeau4** [comment]
File are now the same in both repositories.  CMOR (3.2.4) branch and CMIP6-CMOR-TABLES (master)
