### ISSUE TITLE
"hr" frequency for CMIP6_AERhr.json table does not exist in CMIP6_CV

### ISSUE THREAD

**Issue by mpmoine** [PCMDI/cmip6-cmor-tables#59]
@dnadeau4 
Dear Denis,

The `CMIP6_AERhr.json` table has an associated frequency labelled `hr`. However this label does not exists in CMIP6_CV world (only `1hr` is defined).

Who is right, the table or the CV?

Thanks,
Marie-Pierre.

**Comment by dnadeau4** [comment]
@mpmoine it should be `1hr`, but it is defined as `hr` in Martin's database.

@martinjuckes can you check your `miptable` item `aerhourly` in dreq.xml?  

`em1hr` :`1hr`
`em1hrclimmon`: `1hrClimMon`

Denis

**Comment by dnadeau4** [comment]
@taylor13 @martinjuckes  Can we change AERhr frequency to "1hr"?

**Comment by martinjuckes** [comment]
Changed in 01.00.11
