### ISSUE TITLE
ocean axes in Amon table

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmip6-cmor-tables#6]
The axes in [CMIP6_Amon.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_Amon.json#L350-L481) look eerily like ocean axes:

```
...
        "depth2000m": {
            "standard_name": "depth", 
            "units": "m", 
            "axis": "Z", 
            "long_name": "coordinate value for 2000 m ocean depth", 
            "climatology": "", 
            "formula": "", 
            "must_have_bounds": "no", 
            "out_name": "depth", 
            "positive": "down", 
            "requested": "", 
            "requested_bounds": "", 
            "stored_direction": "", 
            "tolerance": "", 
            "type": "double", 
            "valid_max": "", 
            "valid_min": "", 
            "value": "2000", 
            "z_bounds_factors": "", 
            "z_factors": "", 
            "bounds_values": ""
}, 
...
```

It'd be good to check and update these tables

**Comment by dnadeau4** [comment]
I put all the axes in all the tables, I am thinking of creating a new table just for axes.  CMOR will only pull the axes defined with cmor_axis(), so it does not really matter where they are as long as they can be found after calling cmor_load_table().

**Comment by durack1** [comment]
@dnadeau4 FYI, the axes from [`CMIP6_Amon.json`](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_Amon.json) are now included in [`CMIP6_CVs/CMIP6_coordinate.json`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_coordinate.json) - at least the version that preceded `01.beta.32`

**Comment by dnadeau4** [comment]
This is what we have now. The differences are `valid_min` and `valid_max` which are set:

```
...
        "depth2000m": {
            "standard_name": "depth",
            "units": "m",
            "axis": "Z",
            "long_name": "depth",
            "climatology": "",
            "formula": "",
            "must_have_bounds": "no",
            "out_name": "depth",
            "positive": "down",
            "requested": "",
            "requested_bounds": "",
            "stored_direction": "increasing",
            "tolerance": "",
            "type": "double",
            "valid_max": "2200.0",
            "valid_min": "1980.0",
            "value": "2000",
            "z_bounds_factors": "",
            "z_factors": "",
            "bounds_values": ""
        },
...
```

**Comment by durack1** [comment]
@dnadeau4 my point was that there were ocean axes in the `Amon` table.. I think this is now resolved by removing the duplication of `coordinates` into their own json file
