### ISSUE TITLE
CMIP6_coordinate.json time2 is missing climatology

### ISSUE THREAD

**Issue by jonseddon** [PCMDI/cmip6-cmor-tables#67]
Hi,
The coordinate time2 refers to climatologies I believe from the data request http://clipc-services.ceda.ac.uk/dreq/u/7a97ae58-8042-11e6-97ee-ac72891c3257.html

However, climatology is not set on this coordinate in CMIP6_coordinate.json. Therefore I think that line 2141 in this file (https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_coordinate.json#L2141) should change from:
` "climatology": "",`
to:
` "climatology": "yes",`

CMOR doesn't currently handle climatology variables correctly, but it does after this change is made.

Thanks,

Jon

**Comment by wachsylon** [comment]
Hi,
I would like to add that all time axes attributes needs to be checked because three of these axes are equal to each other and different to what the DREQ suggests.
Thanks and regards,
Fabi

**Comment by jonseddon** [comment]
Similarly, I think that time3 for the diurnal cycle variables needs the climatology attribute setting (https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_coordinate.json#L2158).

**Comment by dnadeau4** [comment]
@jonseddon you are right,  time2 is climatology, time3 is diurnal and the output name is always time. 

Right, now I changed CMOR to handle `reftime` which is a reference time axis for the decadal experiment 

They are some `time2` test that I found `test_python_joerg_tim2_clim_02.py` works, but the other one are still in `cmor2` and not reading JSON files or the CMIP6 tables.  

I will convert them to CMOR3 for version 3.2.4.

**Comment by dnadeau4** [comment]
@wachsylon  can you be more specific?   All tables are created from `DREQ` `XML` database except the `formula_variables` which I extracted from `CMIP5` tables.

**Comment by dnadeau4** [comment]
` climatology` field is not part of DREQ XML database. 

Some fields are kept blank in the JSON file.... I don't really have to read this from CMIP5.

https://github.com/PCMDI/xml-cmor3-database/blob/master/src/convertXML.py#L463-L474

**Comment by dnadeau4** [comment]
Actually,  I already read CMIP5 tables to add all missing axes from `DREQ` into the tables.  I could just piggy back on that code to extract/add the missing fields for each axis. 

https://github.com/PCMDI/xml-cmor3-database/blob/master/src/convertXML.py#L1137-L1212

**Comment by dnadeau4** [comment]
@jonseddon I will force `"climatology": "yes"` in the next table release `01.00.11`.

**Comment by wachsylon** [comment]
OK I only was surprised and wanted to emphasize that time axes `time`, `time2` and `time3` are equal to each other in CMIP6_coordinate.json. If you add `"climatology": "yes"` to the diurnal cycle axis  `time3` and the climatology axis `time2`, they are technically still equal in CMIP6_coordinate.json . However, I understand why two axes exist. 
Thanks and sorry for the confusing comment,
Fabi

**Comment by jonseddon** [comment]
@dnadeau4 Brilliant, thanks for that.

**Comment by dnadeau4** [comment]
@jonseddon  I have a branch for DREQ 01.00.11, but I can't release it with CMOR 3.2.3.  We move the `frequency` to `variables` section in the `CMIP6` tables.   This break back compatibility with CMOR 3.2.3

https://github.com/PCMDI/cmip6-cmor-tables/tree/01.00.11

**Comment by dnadeau4** [comment]
I also added `climatology:yes` to `time3`
