### ISSUE TITLE
CMIP6_Odec.json is missing approx_interval

### ISSUE THREAD

**Issue by jonseddon** [PCMDI/cmip6-cmor-tables#68]
Hi, approx_interval in CMIP6_Odec.json is blank, which causes CMOR to generate the following error when writing decadal data:
```
C Traceback:
! In function: cmor_check_interval
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: approximate time axis interval is defined as 0.000000 seconds (0.000000 days), for value 1 we got a difference of 311040000.000000 seconds (3600.000000 days), which is inf % , seems too big, check your values
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```

Should this be set to 3650?

Thanks,

Jon

**Comment by dnadeau4** [comment]
This is the table I created for the `approximation interval`,  unfortunately, the tables keep changing and as you know it is hard to keep up. 

So,  I wrote a script about what table is added/deleted for DREQ, but forgot to update this list last time.  

https://github.com/PCMDI/xml-cmor3-database/blob/master/src/CMOR3Template.py#L129-L308
