### ISSUE TITLE
expcfe and expfe

### ISSUE THREAD

**Issue by MartinaSt** [PCMDI/cmip6-cmor-tables#69]
There are two variable names in use for the CF 'sinking_mole_flux_of_particulate_iron_in_sea_water':
Emon: expcfe
Oyr: expfe
I guess that there is a typo in the Emon table and it should be also 'expfe'.

**Comment by dnadeau4** [comment]
The 2 variables are still problematic in version `01.00.11`.   I have a branch and did not release yet, for the `frequency` attributes have moved to the `variable` section which break back compatibility with `CMOR 3.2.3`.   I will make release them with `CMOR 3.2.4` hopefully next week. 

https://github.com/PCMDI/cmip6-cmor-tables/blob/01.00.11/Tables/CMIP6_Emon.json#L1330
https://github.com/PCMDI/cmip6-cmor-tables/blob/01.00.11/Tables/CMIP6_Oyr.json#L880
