### ISSUE TITLE
license regex in CMIP6_CV.json

### ISSUE THREAD

**Issue by jonseddon** [PCMDI/cmip6-cmor-tables#71]
Hi,
I think that the regex for `license` in CMIP6_CV.json isn't quite correct. It doesn't match our license text: `CMIP6 model data produced by MOHC is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License (https://creativecommons.org/licenses). Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file). The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law.`

I believe that:
`global attribute in this file) .*\\. The data`
should be changed to:
`global attribute in this file).*\\. The data`
(i.e. remove the space) to match the case where an additional URL isn't specified.

Thanks,

Jon

**Comment by dnadeau4** [comment]
Thanks @jonseddon I fix it and push in the latest tables `01.00.12` released by @martinjuckes.
https://github.com/PCMDI/cmip6-cmor-tables/blob/01.00.12/Tables/CMIP6_CV.json#L12

**Comment by jonseddon** [comment]
@dnadeau4 This looks like it's crept back in at `1.00.13`: https://github.com/PCMDI/cmip6-cmor-tables/blob/01.00.13/Tables/CMIP6_CV.json#L1279 and https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json#L1279

**Comment by dnadeau4** [comment]
I just fixed it and move the tag 01.00.13 and CMOR-3.2.5.

https://github.com/PCMDI/cmip6-cmor-tables/commit/16c7d9a62ec26cf1f8a783652f3274a3dedb8c07#diff-93fc0e51bff2e42c876cf25ced46bd98

Thanks!
Denis
