### ISSUE TITLE
Sea Ice Albedo

### ISSUE THREAD

**Issue by martinvancop** [PCMDI/cmip6-cmor-tables#75]
Hi CMIP6,

I just noticed that sea ice albedo has been dropped from the data request. I think this is unfortunate and hope we can reverse this decision. Here is why.

As far as I understand it, dropping albedo may introduce some duplication, because incident and reflected shortwave fluxes are also required. However, I know at least 3 important climate groups who may not provide these two fields (for technical / time reasons). As a result, sea ice albedo will not be diagnosable from CMIP6 simulations.

As you may know, sea ice albedo is quite important for the energy budget of our planet. This is why it is also very often used as a tuning parameter (sometimes well out of observation range). It is also very well observed from space and in situ.

For these reasons, dropping sea ice albedo could be quite a significant gap for rather a small space gain (monthly 2D field).

I'm sorry to use this forum to make this point if irrelevant.

Best wishes,

Martin Vancoppenolle
IPSL

**Comment by martinjuckes** [comment]
OK : discussion continued on https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/185
