### ISSUE TITLE
Tos is spelled tso in 3hr table

### ISSUE THREAD

**Issue by jvegasbsc** [PCMDI/cmip6-cmor-tables#76]
Sea surface temperature is called tso in table 3hr while is called tos in all the others.
It looks like a typo

Thanks,
Javi

**Comment by dnadeau4** [comment]
I submitted your issue to cmip6dr repository.

**Comment by dnadeau4** [comment]
Thanks! This is now fixed.
https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_3hr.json#L358
